name: Push to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Add Hugging Face remote
        run: |
          git remote add hf https://RamanathanB:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/RamanathanB/Simple_LLM_Chat_Application

      - name: Pull from Hugging Face (IMPORTANT)
        run: |
          git pull hf main --rebase

      - name: Push to Hugging Face
        run: |
          git push hf main
